# Generated by Django 2.2 on 2019-04-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dagstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('task_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('dag_id', models.CharField(max_length=250, unique=True)),
                ('execution_date', models.DateTimeField()),
                ('state', models.CharField(max_length=20)),
                ('try_number', models.IntegerField(blank=True)),
                ('queue', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'task_instance',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
