# Generated by Django 2.2 on 2019-04-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190418_0741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskInstance',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
